version: '3.8'

services:
  beaverhabits:
    image: daya0576/beaverhabits:latest
    container_name: beaverhabits
    user: "${UID}:${GID}"  # Dynamically sets the user ID and group ID
    environment:
      - FIRST_DAY_OF_WEEK=0
      - HABITS_STORAGE=USER_DISK
      - MAX_USER_COUNT=1
    volumes:
      - /home/docker/beaver/data:/app/.user/
    restart: unless-stopped
    networks:
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"
      - "traefik.http.routers.beaverhabits-http.entrypoints=http"
      - "traefik.http.routers.beaverhabits-http.rule=Host(`beaver.local.brett-nelson.com`)"
      - "traefik.http.middlewares.beaverhabits-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.beaverhabits-http.middlewares=beaverhabits-https-redirect"
      - "traefik.http.routers.beaverhabits-https.entrypoints=https"
      - "traefik.http.routers.beaverhabits-https.rule=Host(`beaver.local.brett-nelson.com`)"
      - "traefik.http.routers.beaverhabits-https.tls=true"
      - "traefik.http.routers.beaverhabits-https.tls.certresolver=cloudflare"
      - "traefik.http.routers.beaverhabits-https.service=beaverhabits-service"
      - "traefik.http.services.beaverhabits-service.loadbalancer.server.port=8080"

networks:
  proxy:
    external: true  # Assumes you have an external network named 'proxy'

