services:
  bytestash:
    image: "ghcr.io/jordan-dalby/bytestash:latest"
    restart: always
    volumes:
      - /home/docker/bytestash/data:/data/snippets
    networks:
      - proxy
    environment:
      # See https://github.com/jordan-dalby/ByteStash/wiki/FAQ#environment-variables
      BASE_PATH: ""
      JWT_SECRET: #enter a random secret
      TOKEN_EXPIRY: 24h
      ALLOW_NEW_ACCOUNTS: "true"
      DEBUG: "true"
      DISABLE_ACCOUNTS: "false"
      DISABLE_INTERNAL_ACCOUNTS: "false"

      # See https://github.com/jordan-dalby/ByteStash/wiki/Single-Sign%E2%80%90on-Setup for more info
      OIDC_ENABLED: "false"
      OIDC_DISPLAY_NAME: ""
      OIDC_ISSUER_URL: ""
      OIDC_CLIENT_ID: ""
      OIDC_CLIENT_SECRET: ""
      OIDC_SCOPES: ""
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"
      - "traefik.http.routers.bytestash.entrypoints=http"
      - "traefik.http.routers.bytestash.rule=Host(`bytestash.local.brett-nelson.com`)"
      - "traefik.http.middlewares.bytestash-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.bytestash.middlewares=bytestash-https-redirect"
      - "traefik.http.routers.bytestash-secure.entrypoints=https"
      - "traefik.http.routers.bytestash-secure.rule=Host(`bytestash.local.brett-nelson.com`)"
      - "traefik.http.routers.bytestash-secure.tls=true"
      - "traefik.http.routers.bytestash-secure.tls.certresolver=cloudflare"
      - "traefik.http.routers.bytestash-secure.service=bytestash"
      - "traefik.http.services.bytestash.loadbalancer.server.port=5000" # Internal port exposed by the container

networks:
  proxy:
    external: true
